### ISSUE TITLE
autoRestart not work

### ISSUE THREAD

**Issue by lichnow** [vlazh/node-hot-loader#21]
```
Server has started:
- RestAPI: http://127.0.0.1:3333/api
- RestDocs:
    [DEFAULT]:
      <app>: http://127.0.0.1:3333/api-docs/app

    [V1]:
      <app>: http://127.0.0.1:3333/api-docs/v1/app
ReferenceError: kkk is not defined
    at Object.<anonymous> (/Users/nangongmo/Code/one/apps/server/dist/0.aebffefb798ce7a83fcc.hot-update.js:35:1)
    at __webpack_require__ (/Users/nangongmo/Code/one/apps/server/dist/server.js:9803:32)
    at Object._requireSelf [as require] (/Users/nangongmo/Code/one/apps/server/dist/server.js:9943:15)
    at Object.apply (/Users/nangongmo/Code/one/apps/server/dist/server.js:10558:22)
    at /Users/nangongmo/Code/one/apps/server/dist/server.js:10159:36
    at Array.forEach (<anonymous>)
    at internalApply (/Users/nangongmo/Code/one/apps/server/dist/server.js:10157:21)
    at /Users/nangongmo/Code/one/apps/server/dist/server.js:10098:24
    at waitForBlockingPromises (/Users/nangongmo/Code/one/apps/server/dist/server.js:10054:55)
    at /Users/nangongmo/Code/one/apps/server/dist/server.js:10096:22
[HMR] Updated modules:
[HMR]  - 0
[HMR] Update applied.

✔ build successfully!
[HMR] App is up to date.
[HMR] Updated modules:
[HMR]  - 0
[HMR] Update applied.

✔ build successfully!
[HMR] App is up to date.
```

```typescript
new NodeHotLoaderWebpackPlugin({
                        force: true, // boolean. true - always launch entries, false (by default) - launch entries only in watch mode.
                        fork: true, // boolean | string[]. For example ['--key', 'key value'].
                        args: ['start'], // string[]. For example ['--arg1', 'arg2'].
                        autoRestart: true, // boolean
                    }),
````

```typescript
const creator = createApp({
    configs,
    register: async ({ BootModule }) => {
        const app = await NestFactory.create<NestFastifyApplication>(
            BootModule,
            new FastifyAdapter(),
            {
                cors: true,
                logger: ['error', 'warn'],
            },
        );
        return app;
    },
    hooks: {
        inited: (configure, util) => buildApi(configure, util, api),
        started: (app, util) => util.get(ApiUtil).registerDocs(app),
        hmr: (instance) => {
            if (module.hot) {
                module.hot.accept((err: any) => console.error(err));
                module.hot.dispose(async () => instance.close());
            }
        },
        echo: (configure) => echoApi(configure),
    },
});
run(creator);

```

after catch error, it not restart

**Comment by lichnow** [comment]
because
```
if (["abort", "fail"].indexOf(module.hot.status()) >= 0) {
```
so 
change `module.hot.accept((err: any) => console.error(err))` to `module.hot.accept()` it worked

**Comment by vladzdev** [comment]
autoRestart option means that only if hot update failed then app will be restarted. Your case looks like that, when you provide ’module.hot.accept()’ without callback then module is not accepted and app restarting. If you provide callback then module accept hot update and app does not need to restart because your code is hot updated already.

**Comment by vladzdev** [comment]
Closed due to inactivity.
