### ISSUE TITLE
Invalid Configuration Object

### ISSUE THREAD

**Issue by myronu** [vlazh/node-hot-loader#8]
I downloaded node-hot-loader and tried to launch it, but I get this error:

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration should be an object.
    at webpack (C:\Users\myron.uecker\workspace\eagle-zion\eagle\documentsearchclientweb\client\node_modules\webpack\lib\webpack.js:19:9)
    at Promise.resolve.then.then.then.then.webpackConfig (C:\Users\myron.uecker\workspace\eagle-zion\eagle\documentsearchclientweb\client\node_modules\node-hot-loader\lib\loader.js:85:297)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

```

our webpack config is set up with

`module.exports = (env) => {
...`

I did a quick search and found this link, which suggests that instead of "webpackConfig" the code should use "webpackConfig()"
https://github.com/webpack/webpack/issues/6960

**Comment by vladzdev** [comment]
@myronu, thanx!
Added support for webpack config function in [1.11.0](https://github.com/vlazh/node-hot-loader/blob/master/CHANGELOG.md#1110-2018-08-30), but you need to use the latest version with bugfixes.

**Comment by vladzdev** [comment]
Feel free to reopen issue.
